# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15d2c19c8e10b0a75bdf775a811a461458e9f4d16690153e460399287fff8a8b1a2f90be0db14c3a136ed4146762c3000f67535645bf75ed74a9a54bca4de1da

test:
  secret_key_base: 1a2ae64dd9a33f4d5a2b65d9862a86e1354b46f469a66db2e191d1d9de1ebace2466c80a009651d091db42b91b960adec67421e708725e534f3995437cd70879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
